export const SYSTEM_APPS_PONG_MOVE_SPEED = 2;
export const SYSTEM_APPS_PONG_X_POS = 100;
export const SYSTEM_APPS_PONG_HEIGHT = 300;
export const SYSTEM_APPS_PONG_WIDTH = 20;
export const SYSTEM_APPS_BALL_WIDTH = 50;
